### ISSUE TITLE
[Bug]: teamsSSO not working in teams v2 app client

### ISSUE THREAD

**Issue by yonggang-xiao** [microsoft/teams-ai#1395] opened 2024-03-13 04:45 UTC
### Language

Javascript/Typescript

### Version

1.1.1

### Description

My bot using teams SSO, only in teams v2 app there is no response when call app.getTokenOrStartSignIn().
I have tested using teams v1 app, teams v1 browser, teams v2 browser, all SSO flow are OK.
```
authentication: {
    settings: {
      graph: {
          scopes: ['User.Read'],
          msalConfig: {
              auth: {
                  clientId: config.aadAppClientId,
                  clientSecret: config.aadAppClientSecret,
                  authority: `${config.aadAppOauthAuthorityHost}/${config.aadAppTenantId}`,
              }
          },
          signInLink: `https://${process.env.BOT_DOMAIN}/auth-start.html`,
          endOnInvalidMessage: true
      }
    },
    autoSignIn: (context) => {
      return Promise.resolve(false);
    }
  }
```

I get token manually
```
const token = await app.getTokenOrStartSignIn(context, state, 'graph');
```

I can not see any error log in Azure app's log stream.

### Reproduction Steps

```bash
1.using teams SSO
2.call app.getTokenOrStartSignIn()
3.or first call app.authentication.signOutUser()

My teams app version 24033.812.2721.9190 (24033.812.2721.9190)
and macOS 13.6.4
```

**Comment by corinagum** [comment] 2024-03-14 21:54
This would appear to be a Teams bug that needs to be filed. Let me discuss internally and get back to you.

**Comment by singhk97** [comment] 2024-03-16 01:17
@yonggang-xiao Hey what error are you running into when you say there's no response. Do you not get a prompt to initiate signin in the Teams client? Can you verify if the E2E flow works when `autoSign` is set to true.

**Comment by yonggang-xiao** [comment] 2024-03-24 02:08
I have tested the `autoSignIn` set to true, seems working now. But the auto sign in won't trigger onUserSignInSuccess() handler, so there is no response message to user. This confused me, user need input message again to interactive with the bot.

**Comment by singhk97** [comment] 2024-03-25 11:05
> I have tested the `autoSignIn` set to true, seems working now. But the auto sign in won't trigger onUserSignInSuccess() handler, so there is no response message to user. This confused me, user need input message again to interactive with the bot.

Hmm that's not supposed to be happening. Is this only when using the Teams v2 client?

P.S

https://github.com/microsoft/teams-ai/blob/798d49c75c640522afb201578deeffb8dd0d94b4/js/packages/teams-ai/src/authentication/Authentication.ts#L153-L162

The `onUserSignInSuccess` handler would execute only if the user initiated the auth flow by sending a message to the bot. It should work in `autoSignIn` is set to true as well.

**Comment by yonggang-xiao** [comment] 2024-03-27 00:48
I found the problem in all teams client.

**Comment by singhk97** [comment] 2024-08-08 15:47
Hi @yonggang-xiao can you share if the issue is still persisting.

**Comment by singhk97** [comment] 2024-09-03 21:41
I'm closing this issue for now. @yonggang-xiao please feel free to re-open if the issue is still persisting.

**Closed by singhk97** 2024-09-03 21:41 UTC
Labels: bug, dev support
