### ISSUE TITLE
[Bug]: `yarn build` failed for `Teams Chef Bot` sample

### ISSUE THREAD

**Issue by MuyangAmigo** [microsoft/teams-ai#1432] opened 2024-03-21 08:08 UTC
### Language

Javascript/Typescript

### Version

latest

### Description

When executing the `yarn build` for `Teams Chef Bot` sample, it fails with unresolved dependency.
I expect I could do this from a specific sample, not from the root folder.

![image](https://github.com/microsoft/teams-ai/assets/11220663/123d23ee-a3f2-432e-bd41-29712ea462fd)

### Reproduction Steps

```bash
1. Clone the teams-ai library
2. cd to the teams chef sample
3. yarn install
4. yarn build

**Comment by therealjohn** [comment] 2024-03-21 12:38
Inside the sample directory, no `yarn build` is necessary. `yarn build` should only be run in the `js` directory when trying to create a local build of the teams-ai package to use with the sample.

**Comment by dylanw-oss** [comment] 2024-03-21 17:43
this is duplicate of #1405

**Comment by dylanw-oss** [comment] 2024-03-21 17:47
> Inside the sample directory, no `yarn build` is necessary. `yarn build` should only be run in the `js` directory when trying to create a local build of the teams-ai package to use with the sample.

@therealjohn, how about provision/deploy to Azure? I think we need to run `yarn install && yarn build` in sample folder. see #1428

**Comment by corinagum** [comment] 2024-03-21 20:54
Closing this as duplicate. @dylanw-oss I have a meeting scheduled with therealjohn to discuss the above, so in case he doesn't get to a reply I will get back to you.

**Closed by corinagum** 2024-03-21 20:54 UTC
Labels: bug
