### ISSUE TITLE
[Bug]: gpt-4o and gpt-4o-mini models not working for assistants

### ISSUE THREAD

**Issue by stuart-pebble** [microsoft/teams-ai#1861] opened 2024-07-20 23:10 UTC
### Language

Javascript/Typescript

### Version

latest

### Description

When using OpenAI Assistants, only some models work, not all of them. None of the gpt4o variants work. Its worth noting that gpt-4-1106-preview and gpt-4-turbo models do work.

### Reproduction Steps

```bash
1. Build an MS Teams Assistant API bot using the defaults 
2. Modify the OpenAI Assistant to use the preferred model
3.
...
```

**Comment by corinagum** [comment] 2024-07-22 16:51
Hi @stuart-pebble, which sample are you using? [Order bot](https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai-apps/e.assistants-orderBot)? or Math bot?

**Comment by stuart-pebble** [comment] 2024-07-22 19:15
I'm not using a sample, I'm using the MS Teams Toolkit to create one from scratch using:

Create New App
![image](https://github.com/user-attachments/assets/7655c863-0323-47b1-92eb-53b8c2ae28c3)

Custom Copilot:
![image](https://github.com/user-attachments/assets/f9937e4a-ad71-47fe-9cdc-c0b3dc71c7e2)

AI Agent:
![image](https://github.com/user-attachments/assets/81f4664a-438d-47b5-ad4c-2a1b6cfb3195)

Build with Assistants API (Preview)
![image](https://github.com/user-attachments/assets/05e99dda-c42d-4edf-a0be-48abef740b6d)

JavaScript
![image](https://github.com/user-attachments/assets/d091197d-fb69-4544-ba24-3883297ae40e)

My objective is a simple RAG use case where users can ask questions with responses based on RAG from an OpenAI configured vector store. I can work around the gpt-4o-mini issue and select the gpt-4-turbo model in the short term but its not optimal.

FYI: I'm also having the same issues as https://github.com/microsoft/teams-ai/issues/1585 where, using the defaults, the OpenAI RAG functions are ignored. I'm currently exploring options to either update the node module or redeploy using the orderbot example.

**Comment by corinagum** [comment] 2024-08-05 20:58
@stuart-pebble what errors are you getting? What is your sample code? We will need information in order to determine the bug.

**Comment by stuart-pebble** [comment] 2024-08-06 08:49
If I configure the Assistant in OpenAI with gpt-4o or gpt-4o-mini all I see in the MS Teams chabot is " There was an error". If I change to one of the other models it just works.

**Comment by lariar** [comment] 2024-08-10 01:50
Came here to confirm also seeing this problem. Took 3 days to figure out my own chatbot would work by reverting it back to GPT-4-turbo on the OpenAI side.

**Comment by yikwen** [comment] 2024-08-15 12:55
I faced this issue as well where older GPT models worked fine and things started breaking when changed to GPT-4o. Inspecting the completions coming from GPT-4o, I found that the issue was with GPT-4o not following instructions in creating the plan using SAY and DO commands (I'm using sequence augmentation btw).

I added the following sentences to `skprompt.txt` and it performed better subsequently.

> - Provide your response in the form of a JSON object following the format provided at the end of these instructions
> - If the user's request matches an action you can perform, add that action to the JSON plan as a DO command. For anything you want to ask or tell the user, add the text to the JSON plan as a SAY command.

**Comment by Stevenic** [comment] 2024-08-19 22:22
Thanks for the hint @yikwen. We're going to look into using the new structured outputs support for plan generation which should help resolve the issue.

**Comment by Stevenic** [comment] 2024-08-19 22:23
@stuart-pebble I think the issue you're hitting is something different so I'll try to reproduce it

**Comment by Benjiiim** [comment] 2024-09-02 08:57
> We're going to look into using the new structured outputs support for plan generation which should help resolve the issue.

The perspective to have Teams AI Library using structured outputs and GPT-4o-mini is really exciting! I can't wait to see the impact it will have, especially on cost-effectiveness.
Is this something that we can expect to get our hands on soon?

**Comment by aacebo** [comment] 2024-10-22 20:42
closing this since its related to the assistants v2 work that is being tracked in another ticket. If interested please refer to https://github.com/microsoft/teams-ai/issues/1585 for updates.

**Closed by aacebo** 2024-10-22 20:42 UTC
Labels: bug
