### ISSUE TITLE
[Bug]: Sample env files missing from 'a.teamsChefBot' js sample

### ISSUE THREAD

**Issue by rmatesick-nw** [microsoft/teams-ai#1641] opened 2024-05-13 15:12 UTC
### Language

Javascript/Typescript

### Version

latest

### Description

The README in the `src/js/samples/04.ai-apps/a.teamsChefBot` of the main branch refers to populating the sample env files, however that entire `env` folder is missing.  It appears to have been removed with PR #1511

### Reproduction Steps

1. Browse to https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai-apps/a.teamsChefBot
2. Notice the entire `env` folder and its contents are missing.

**Comment by corinagum** [comment] 2024-05-14 17:06
duplicate of #1564

**Closed by corinagum** 2024-05-14 17:06 UTC
Labels: bug
