### ISSUE TITLE
[Bug]: Assistant functionality doesn't work as expect in the TS version

### ISSUE THREAD

**Issue by chenxizhang** [microsoft/teams-ai#1807] opened 2024-07-06 09:32 UTC
### Language

Javascript/Typescript

### Version

latest

### Description

I am using Azure OpenAI service, and have set the endpoint in the code, I can run the test successfully in the "Teams test client", and it can answer the basic question, but it will not invoke the "file_search" tool even though I have configured it well and it worked in the python version of the toolkit.

![image](https://github.com/microsoft/teams-ai/assets/1996954/ea778600-d0b7-41b9-b63e-a703c9b451cd)

### Reproduction Steps

```bash
1. Create your assistant in Azure OpenAI, and enable "file_search" tool.
2. Create your teams app by the Teams toolkit template, 'Custom Copilot' => 'AI Agent' and complete the configuration in .env
3. Debug it in the "Teams Test client'
```

**Comment by corinagum** [comment] 2024-07-08 17:26
Hi @chenxizhang, this appears to be a duplicate of the feature work for [assistants citations](https://github.com/microsoft/teams-ai/issues/1590). Closing this in favor of the other for tracking.

**Closed by corinagum** 2024-07-08 17:26 UTC
Labels: bug
