### ISSUE TITLE
[JS] Fix: ME Auth card title is a fixed string

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#1445] opened 2024-03-25 12:05 UTC

**Comment by corinagum** [comment] 2024-03-25 17:08
Isn't this a duplicate of #1417

**Comment by singhk97** [comment] 2024-03-25 17:10
This ticket is for the JS fix. C#, PY fixes will have it's own ticket. This will help in keeping track the state across the 3 sdks.

**Closed** 2024-03-25 17:24 UTC
Labels: bug, JS
